//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseBettingBackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorseBettingSiteEntities : DbContext
    {
        public HorseBettingSiteEntities()
            : base("name=HorseBettingSiteEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<horse> horses { get; set; }
        public virtual DbSet<jockey> jockeys { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<owner> owners { get; set; }
        public virtual DbSet<race> races { get; set; }
        public virtual DbSet<racehorse> racehorses { get; set; }
    }
}
