//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseBettingBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public race()
        {
            this.racehorses = new HashSet<racehorse>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int locationid { get; set; }
    
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racehorse> racehorses { get; set; }
    }
}
