//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseBettingBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class racehorse
    {
        public int id { get; set; }
        public int raceid { get; set; }
        public int horseid { get; set; }
        public Nullable<int> jockeyid { get; set; }
        public int odd { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual horse horse { get; set; }
        public virtual jockey jockey { get; set; }
        public virtual race race { internal get; set; }
    }
}
